version: "3"

services:
  api-gestor:
    container_name: api-gestor
    tty: true
    build: .
    ports:
      - 80:80
      - 8080:8080
      - 433:433
      - 5269:5269
    volumes:
      - .:/workspaces
    networks:
      - rede_local

networks:
  rede_local:
    external: true
    driver: bridge

#   mongo3:
#     container_name: mongo3
#     image: bitnami/mongodb:5.0.17
#     volumes:
#       - mongodb_data:/bitnami/mongodb
#     environment:
#       - MONGODB_ROOT_PASSWORD=root
#       - MONGODB_REPLICA_SET_MODE=primary
#       - MONGODB_REPLICA_SET_KEY=123456
#       - MONGODB_DATABASE=nest

# volumes:
#   mongodb_data:
#     driver: local